default:
  homepage:
    title: Xceptance - The Software Testing Experts
  header:
    topNavigation:
      "1":
        title: Services
      "2":
        title: xlt
      "3":
        title: Unternehmen
      "4":
        title: News
      "5":
        title: Jobs
      "6":
        title: Kontakt
      "7":
        title: Blog
# United States
en_US:
  homepage:
    title: Xceptance - The Software Testing Experts
  slider:
    headline:
      "1": |
        We Test Software.
        Because Quality Matters.
      "2":
        We are 
        Salesforce Commerce Cloud Partner.
      "3":
        XLT - The Open Source Performance Test Tool.
    button:
      "1": Learn More
      "2": Learn More
      "3": Download
  header:
    topNavigation:
      "services": Services
      "xlt": XLT
      "company": Company
      "news": News
      "careers": Careers
      "contact": Contact
      "blog": Blog
      "subNavigation":
        services:
          "overview": Overview
          "salesforce" : Salesforce Commerce Cloud
        xlt:
          "overview" : Overview
          "features" : Features
          "documentation" : Documentation
          "licenseUndSupport" : License & Support
          "download" : Download
  links:
    xlt:
      documentation:
        userManual : User Manual
        releaseNotes : Release Notes
        apiDocumentation : API Documentation
        gitHubReleases : GitHub Releases
        gitHubIssueTracker : GitHub Issue Tracker
        userForum : User Forum
  company:
      headline: |
        Welcome to Xceptance!
        Get to know us. THIS WAY
      button: This way
  footer:
    address:
      "germany": Jena, Germany Headquarters
      "usa": Cambridge, MA, USA
    email:
      "germany": kontakt@xceptance.de
      "usa": contact@xceptance.com
    tel:
      "germany": +49-3641-376300
      "usa": +1-617-225-4335
    linkTexts:
      "aboutUs": About Us
      "contact": Contact
      "services": Services
      "xlt": XLT
      "references": References
      "privacy": Privacy
      "blog": Blog
      "xing": Xing
      "linkedin": LinkedIn
      "twitter": Twitter
      "github": GitHub
    newsTexts:
      "latestNews": Latest News
      "latestNews1": Donation to Wandlungswelten
      "latestNews2": The University Summer Festival
      "latestNews3": Xceptance sparks great ideas
  servicePage:
    overview:
      teaser:
        headline: |
          Inspecting, Observing,
          Reporting.
      functionalTesting:
        manualTesting : Manual Testing
        automatedTesting : Automated Testing
      performanceTesting:
        loadUndPerformanceTesting : Load & Performance Testing
        subHeader :
          serverSidePerformanceTesting : Server-Side Performance
          clientSidePerformanceTesting : Client-Side Performance
      testGuidance: Test Guidance & Support
    salesforce:
      teaser:
        headline: >
          15 Years of Quality Assurance Support
          for Salesforce Commerce Cloud.
        link: http://www.demandware.com/
        linkTitle: Visit Salesforce Commerce Cloud
      intro:
        headline: Partnering For Success
        eCommerce: E-Commerce Testing
        weKnow: We know Salesforce Commerce Cloud
        functionalTesting: Functional Testing
        agileTesting: Agile Testing of Individual Features
        loadAndPerformance: Load and Performance Testing with XLT
        testAutomation: Test Automation
  careerPage:
    jobsOverview:
      headlines:
        weAreHiring: We Are Hiring
        startUp: Start-Up Atmosphere
        workLife: Work-Life Balance
        commitment: Commitment to Integrity
        careerDevelopment: Career Development
        international: International Projects
        roomForCreativity: Room for Creativity
        greatLocations: Great Locations
        valuableInternships: Valuable Internships
        openPositions: Open Positions
        cambridge: in Cambridge, MA
        jena: in Jena, Germany
        erfurt: in Erfurt, Germany
    openPositions:
      locations:
        cambridge:
          qaEngineer: "QA Engineer for Performance and Automated Testing"
        jena:
          lastUndPerformanceTester: "Last- und Performancetester (m/w/d/*)"
          javaEntwickler: "Java-Entwickler (m/w/d/*)"
          technischerMarketingExperte: "Technischer Marketingexperte (m/w/d/*)"
          technischerAutor: "Technischer Autor (m/w/d/*)"
          technischerTester: "Technischer Tester (m/w/d/*)"
          spezialistFürTestAutomatisierung: "Spezialist für Testautomatisierung (m/w/d/*)"
        erfurt:
          technischerTester: "Technischer Tester (m/w/d/*)"
          lastUndPerformanceTester: "Last- und Performancetester (m/w/d/*)"
    jobsBackground:
      title : |
        We look forward to
        welcoming you at Xceptance!
  documentation:
    topNavigation:
      xlt:
        title: XLT
        aboutXLT: About XLT
        quickStart: Quick Start
        baseManual: |
          Base 
          Manual
        advancedLoadTesting: Advanced Load Testing
        testSuites: Test Suites
        howTos: How-Tos
        glossary: Glossary
        releaseNotes: Release Notes
      xtc:
        title: XTC
        basics: Basics
        loadTesting: Load Testing
        monitoring: Monitoring
        integrations: Integrations
        releaseNotes: Release Notes
