default:
  homepage:
    title: Xceptance - The Software Testing Experts
  header:
    topNavigation:
      "1":
        title: Services
      "2":
        title: xlt
      "3":
        title: Unternehmen
      "4":
        title: News
      "5":
        title: Jobs
      "6":
        title: Kontakt
      "7":
        title: Blog
# United States
en_US:
  homepage:
    title: Xceptance - The Software Testing Experts
  slider:
    headline:
      "1": |
        We Test Software.
        Because Quality Matters.
      "2":
        We are 
        Salesforce Commerce Cloud Partner.
      "3":
        XLT - The Open Source Performance Test Tool.
    button:
      "1": Learn More
      "2": Learn More
      "3": Download
  header:
    topNavigation:
      "services":
        title: Services
      "xlt":
        title: XLT
      "company":
        title: Company
      "news":
        title: News
      "careers":
        title: Careers
      "contact":
        title: Contact
      "blog":
        title: Blog
      "subNavigation":
        "services":
          "overview":
            title: Overview
          "salesforce":
            title : Salesforce Commerce Cloud
        "xlt":
          "overview":
            title : Overview
          "features" :
            title : Feature
          "documentation" :
            title : Documentation
          "licenseUndSupport" :
            title : License & Support
          "download" :
            title : Download
  company:
      headline: |
        Welcome to Xceptance!
        Get to know us. THIS WAY
      button: This way
  footer:
    address:
      "germany": Jena, Germany Headquarters
      "usa": Cambridge, MA, USA
    email:
      "germany": kontakt@xceptance.de
      "usa": contact@xceptance.com
    tel:
      "germany": +49-3641-376300
      "usa": +1-617-225-4335
    linkTexts:
      "aboutUs": About Us
      "contact": Contact
      "services": Services
      "xlt": XLT
      "references": References
      "privacy": Privacy
      "blog": Blog
      "xing": Xing
      "linkedin": LinkedIn
      "twitter": Twitter
      "github": GitHub
    newsTexts:
      "latestNews": Latest News
      "latestNews1": Donation to Wandlungswelten
      "latestNews2": The University Summer Festival
      "latestNews3": Xceptance sparks great ideas
  servicePage:
    overview:
      teaser:
        headline: |
          Inspecting, Observing,
          Reporting.
      functionalTesting:
        "1" :
          title : Manual Testing
        "2" :
          title: Automated Testing
      performanceTesting:
        "1" :
          title : Load & Performance Testing
          subHeading :
            "1" :
              title: Server-Side Performance
            "2" :
              title: Client-Side Performance
      testGuidance:
        "1" :
          title : Test Guidance & Support
    salesforce:
      teaser:
        headline: >
          15 Years of Quality Assurance Support
          for Salesforce Commerce Cloud.
        link: http://www.demandware.com/
        linkTitle: Visit Salesforce Commerce Cloud
      intro:
        headline: Partnering For Success
        eCommerce: E-Commerce Testing
        weKnow: We know Salesforce Commerce Cloud
        functionalTesting: Functional Testing
        agileTesting: Agile Testing of Individual Features
        loadAndPerformance: Load and Performance Testing with XLT
        testAutomation: Test Automation
